[project]
name = "stemmabench"
version = "0.0"
description = "Package for benching stemmatology algorithms"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
keywords = ["egg", "bacon", "sausage", "tomatoes", "Lobster Thermidor"]

dependencies = [
  "loguru==0.6.0",
  "nltk==3.7",
  "pydantic==1.9.1",
  "PyYAML==6.0",
  "typer==0.4.1"
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov[all]"
]